package company;

public enum CompanyStructure {
    SOLE,
    PARTNERSHIP,
    LIMITED_LIABILITY_PARTNERSHIP,
    PRIVATE_LIMITED_COMPANY,
    PUBLIC_LIMITED_COMPANY,
    GOVERNMENT_LINKED_COMPANY,
    FOREIGN_COMPANY
}
